import type { ShopState } from "./types"

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString()

/** Sample data so the app isn't empty on first open. */
export function createSeedState(): ShopState {
  return {
    nextInvoiceNumber: 1002,
    vehicles: [
      {
        id: "veh-crv",
        plate: "8KLM204",
        plateState: "CA",
        vin: "5J6RW2H57KL004821",
        year: "2019",
        make: "Honda",
        model: "CR-V",
        trim: "EX",
        color: "Silver",
        mileage: 64210,
        customer: { name: "Dana Ruiz", phone: "(555) 201-3344", email: "dana.ruiz@example.com" },
        createdAt: daysAgo(120),
      },
      {
        id: "veh-f150",
        plate: "TRK4LIF",
        plateState: "TX",
        vin: "1FTEW1EP7JFB27715",
        year: "2018",
        make: "Ford",
        model: "F-150",
        trim: "XLT",
        color: "Blue",
        mileage: 98450,
        customer: { name: "Marcus Thompson", phone: "(555) 448-9012", email: "marcus.t@example.com" },
        createdAt: daysAgo(60),
      },
      {
        id: "veh-camry",
        plate: "7XYZ881",
        plateState: "CA",
        vin: "4T1B11HK8KU732904",
        year: "2019",
        make: "Toyota",
        model: "Camry",
        trim: "SE",
        color: "White",
        mileage: 41870,
        customer: { name: "Priya Shah", phone: "(555) 732-5561", email: "priya.shah@example.com" },
        createdAt: daysAgo(14),
      },
    ],
    jobs: [
      {
        id: "job-1",
        vehicleId: "veh-crv",
        title: "Oil change & tire rotation",
        notes: "Full synthetic 0W-20. Rotated tires, set pressures to 35 psi.",
        technician: "Marcus T.",
        mileage: 58900,
        status: "completed",
        items: [
          { id: "li-1", type: "labor", description: "Oil & filter change", quantity: 0.5, unitPrice: 145 },
          { id: "li-2", type: "labor", description: "Tire rotation", quantity: 0.3, unitPrice: 145 },
          { id: "li-3", type: "part", description: "Synthetic 0W-20 (qt)", quantity: 4, unitPrice: 9.5 },
          { id: "li-4", type: "part", description: "Oil filter", quantity: 1, unitPrice: 12.99 },
        ],
        createdAt: daysAgo(90),
        completedAt: daysAgo(90),
        invoiceId: "inv-1001",
      },
      {
        id: "job-2",
        vehicleId: "veh-crv",
        title: "Front brake pads & rotors",
        notes: "Front pads at 2mm. Replaced pads and rotors, flushed brake fluid.",
        technician: "Marcus T.",
        mileage: 64210,
        status: "completed",
        items: [
          {
            id: "li-5",
            type: "labor",
            description: "Replace front pads & rotors",
            quantity: 1.8,
            unitPrice: 145,
          },
          { id: "li-6", type: "part", description: "Ceramic brake pads (front)", quantity: 1, unitPrice: 89 },
          { id: "li-7", type: "part", description: "Brake rotor — front", quantity: 2, unitPrice: 82 },
          { id: "li-8", type: "part", description: "Brake fluid DOT 3 (qt)", quantity: 1, unitPrice: 14.5 },
        ],
        createdAt: daysAgo(1),
        completedAt: daysAgo(0),
        invoiceId: null,
      },
      {
        id: "job-3",
        vehicleId: "veh-f150",
        title: "Check engine light diagnosis",
        notes: "P0300 random misfire. Inspecting coils and plugs.",
        technician: "Sam K.",
        mileage: 98450,
        status: "in_progress",
        items: [{ id: "li-9", type: "labor", description: "Diagnostic", quantity: 1, unitPrice: 145 }],
        createdAt: daysAgo(0),
        completedAt: null,
        invoiceId: null,
      },
    ],
    invoices: [
      {
        id: "inv-1001",
        number: 1001,
        vehicleId: "veh-crv",
        customer: { name: "Dana Ruiz", phone: "(555) 201-3344", email: "dana.ruiz@example.com" },
        vehicleLabel: "2019 Honda CR-V EX",
        plate: "CA 8KLM204",
        vin: "5J6RW2H57KL004821",
        mileage: 58900,
        jobs: [
          {
            jobId: "job-1",
            title: "Oil change & tire rotation",
            notes: "Full synthetic 0W-20. Rotated tires, set pressures to 35 psi.",
            technician: "Marcus T.",
            items: [
              {
                id: "li-1",
                type: "labor",
                description: "Oil & filter change",
                quantity: 0.5,
                unitPrice: 145,
              },
              { id: "li-2", type: "labor", description: "Tire rotation", quantity: 0.3, unitPrice: 145 },
              { id: "li-3", type: "part", description: "Synthetic 0W-20 (qt)", quantity: 4, unitPrice: 9.5 },
              { id: "li-4", type: "part", description: "Oil filter", quantity: 1, unitPrice: 12.99 },
            ],
          },
        ],
        taxRate: 0.0825,
        status: "paid",
        createdAt: daysAgo(90),
        paidAt: daysAgo(90),
      },
    ],
  }
}
